version: '3'
services:
  web:
    image: 172.31.44.24:8083/spring-boot-websocket-chat-demo:latest_${JOBNAME}-${BUILDNUM}
    ports:
      - "8040:8080"
    networks:
      - overlay
    env_file:
      - ./secret-stuff.env
    deploy:
      replicas: 2

networks:
  overlay:
    external:
      name: epicnetwork
